### PR TITLE
Sniff the file instead of relying on the file extension

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by nsoranzo** [comment]
@dannon Thanks! Can you do a release when you have time? I already have the 2 small changes needed by Galaxy in `lib/galaxy/datatypes/converters/interval_to_tabix_converter.py`

**Comment by dannon** [comment]
Heh, I was just making those same changes

**Comment by nsoranzo** [comment]
Seems it's the only place `already_compressed` was used.

**Comment by dannon** [comment]
Yep, I think so.  I don't _think_ we will have problems with that kwarg going away, either.  Do you?  That was an initial concern, but if Galaxy is always version-locked to the wheel...  Should be fine.

**Comment by nsoranzo** [comment]
I think we need to do:
1. pysam release here
2. Starforge PR to update the wheel
3. Galaxy PR to update `interval_to_tabix_converter.py` and the various requirements file in `lib/galaxy/dependencies/`

**Comment by dannon** [comment]
Yep, exactly.

**Comment by nsoranzo** [comment]
It seems that the Starforge build failed. Unfortunately I don't understand what the problem is, but I am able to replicate the failure:

```
$ python setup.py build
...
cythoning pysam/ctabix.pyx to pysam/ctabix.c

Error compiling Cython file:
------------------------------------------------------------
...
        raise OSError("error when closing file %s" % filename_in)


def is_gzip_file(filename):
    gzip_magic_hex = b'1f8b'
    header = open(filename, 'rb').read(2)
                       ^
------------------------------------------------------------

pysam/ctabix.pyx:808:24: Only single-character string literals can be coerced into ints.
```

Sorry about that, I had some trouble trying to install and test pysam before.

**Comment by dannon** [comment]
@nsoranzo No worries.  This seems familiar, like I've touched on this problem before when working with pysam.  I can look into it if you want.

**Comment by nsoranzo** [comment]
@dannon I'd appreciate that, thanks! It seems it's using `os.open` instead of `open`, but I'm really out of my comfort zone here!

**Comment by dannon** [comment]
Ok, I'll take a look today.

**Comment by dannon** [comment]
@nsoranzo Took a bit of digging for a simple fix, but I've updated the branch and pushed the bump to starforge.  It builds locally for me now.

Edit:  Having issues actually using it, the comparison isn't working like I thought, so don't jump to test quite yet.

**Pull request merged**
